### ISSUE TITLE
TestFailure: cannot import name scripts

### ISSUE THREAD

**Issue by nieder** [daler/pybedtools#192] opened 2016-12-15 02:24 UTC
On OS X with pybedtools 0.7.8, the tests fail with this error:

~~~~
/sw/bin/python2.7 -B setup.py nosetests || exit 2
Cythonizing sources
pybedtools/_Window.pyx has not changed
pybedtools/cbedtools.pyx has not changed
pybedtools/featurefuncs.pyx has not changed
running nosetests
running egg_info
creating pybedtools.egg-info
writing requirements to pybedtools.egg-info/requires.txt
writing pybedtools.egg-info/PKG-INFO
writing top-level names to pybedtools.egg-info/top_level.txt
writing dependency_links to pybedtools.egg-info/dependency_links.txt
writing manifest file 'pybedtools.egg-info/SOURCES.txt'
reading manifest file 'pybedtools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'pybedtools.egg-info/SOURCES.txt'
building 'pybedtools.cbedtools' extension
....
lots of compiling
.....
g++ -L/sw/lib -bundle -L/sw/lib/python2.7/config -lpython2.7 -L/sw/lib -L/sw/lib -I/sw/include build/temp.macosx-10.11-x86_64-2.7/src/bedFile.o build/temp.macosx-10.11-x86_64-2.7/src/fileType.o build/temp.macosx-10.11-x86_64-2.7/src/gzstream.o build/temp.macosx-10.11-x86_64-2.7/pybedtools/featurefuncs.o -L/sw/lib -lstdc++ -lz -o /sw/build.build/pybedtools-py27-0.7.8-1/pybedtools-0.7.8/pybedtools/featurefuncs.so
E
======================================================================
ERROR: Failure: ImportError (cannot import name scripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/sw/build.build/pybedtools-py27-0.7.8-1/pybedtools-0.7.8/pybedtools/__init__.py", line 9, in <module>
    from . import scripts
ImportError: cannot import name scripts

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
~~~~

I am using the Fink packaging system to bring in bedtools-0.26.0 and all the other python requirements for pybedtools. The pybedtools build and test session are run as an unpriviledged user, but if I try to repeat the nosetests command as a normal user, the failure still happens.

**Comment by daler** [comment] 2016-12-17 00:51
Thanks for reporting. I'm unable to reproduce on Linux and have limited access to a dev OSX machine. I'll try to reproduce on OSX as soon as I get a chance. Are you actually using the command `python setup.py nosetests` indicated at the top of the output? I don't think that's enabled in the setup.py, at least, it won't even run at all for me. Does it work if you just do `nosetests` after installing?

pybedtools is on bioconda if you're just looking to install it (http://bioconda.github.io/).

```
conda install pybedtools -c bioconda
```

**Comment by nieder** [comment] 2016-12-17 04:44
Yes, I was using the command `/sw/bin/python2.7 -B setup.py nosetests` to run the tests.  If I switch to running `/sw/bin/nosetests` instead, the error changes to:

````
/sw/bin/nosetests-2.7 || exit 2
E
======================================================================
ERROR: Failure: ImportError (No module named cbedtools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/sw/build.build/pybedtools-py27-0.7.8-2/pybedtools-0.7.8/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: No module named cbedtools

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
````

I've tried with pybedtools both uninstalled and already installed and the error is the same when I run tests from the source folder (both the 0.7.8 tarball and git HEAD).  I've also tried to set PYTHONPATH to the the `build/lib.macosx-10.11-x86_64-2.7` directory inside the source tree, but it doesn't help finding cbedtools.

When pybedtools is installed, these are all the instances I have of 'cbedtools' in my live install tree (these are also in the '$SOURCE/build/lib.macosx-10.11-x86_64-2.7/pybedtools' directory mentioned above for PYTHONPATH):
````
$ dpkg -S cbedtools
pybedtools-py27: /sw/lib/python2.7/site-packages/pybedtools/cbedtools.pxd
pybedtools-py27: /sw/lib/python2.7/site-packages/pybedtools/cbedtools.pyx
pybedtools-py27: /sw/lib/python2.7/site-packages/pybedtools/test/test_cbedtools.py
pybedtools-py27: /sw/lib/python2.7/site-packages/pybedtools/cbedtools.so
pybedtools-py27: /sw/lib/python2.7/site-packages/pybedtools/cbedtools.cxx
pybedtools-py27: /sw/lib/python2.7/site-packages/pybedtools/test/test_cbedtools.pyc
````

**Comment by daler** [comment] 2016-12-17 14:46
It was bugging me why this wasn't being picked up by the travis-ci builds but I think the reason is conda. The travis-ci setup uses conda for speedy installation of dependencies, and that seems to bypass the sys.path and import trickery that nose does.

I'll need to play around with fixing imports and then make sure the CI tests actually test it. But for now the quick fix is to put the tests somewhere else and run 'em there:
 
```bash
cp -r pybedtools/test /tmp
(cd /tmp/test && nosetests)
```

I know it's not ideal and it will be fixed, but does that at least solve the import errors?

**Comment by nieder** [comment] 2016-12-17 15:39
Yes, copying pybedtools/test outside the build dir lets the tests run (I set PYTHONPATH to my built files inside the source tree to make sure it is not using the installed pybedtools). There are several assertion errors, but at least all the tests run.
````
Ran 490 tests in 24.477s

FAILED (SKIP=2, errors=1, failures=8)
````
I'll go through the test failures to see if anything jumps out as fixable on my side first.

**Comment by daler** [comment] 2016-12-17 16:52
There are known issues with bedtools shuffle, where setting the random seed is not consistent -- some of those errors might be from that. I wouldn't expect 9 tests to not pass. Would you send the errors you're getting?

If nothing else, it's clear I need to set up OSX testing on travis-ci.

**Comment by nieder** [comment] 2017-05-30 10:11
Sigh. I lost track of this item and now the errors have changed because [pysam is not building](https://github.com/pysam-developers/pysam/issues/443) here after I upgraded to htslib-1.4
~~~~
xvfb-run /sw/bin/nosetests-2.7 || exit 2
EEEEEEEEE
======================================================================
ERROR: Failure: ImportError (No module named pysam)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/sw/build.build/pybedtools-py27-0.7.9-1/test/regression_tests.py", line 6, in <module>
    import pybedtools
  File "/sw/build.build/pybedtools-py27-0.7.9-1/pybedtools-0.7.9/build/lib.macosx-10.11-x86_64-2.7/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/sw/build.build/pybedtools-py27-0.7.9-1/pybedtools-0.7.9/build/lib.macosx-10.11-x86_64-2.7/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/sw/build.build/pybedtools-py27-0.7.9-1/pybedtools-0.7.9/build/lib.macosx-10.11-x86_64-2.7/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/sw/build.build/pybedtools-py27-0.7.9-1/pybedtools-0.7.9/build/lib.macosx-10.11-x86_64-2.7/pybedtools/helpers.py", line 13, in <module>
    import pysam
ImportError: No module named pysam
...
======================================================================
ERROR: Failure: ImportError (cannot import name scripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/sw/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/sw/build.build/pybedtools-py27-0.7.9-1/test/test_scripts.py", line 1, in <module>
    import pybedtools
  File "/sw/build.build/pybedtools-py27-0.7.9-1/pybedtools-0.7.9/build/lib.macosx-10.11-x86_64-2.7/pybedtools/__init__.py", line 9, in <module>
    from . import scripts
ImportError: cannot import name scripts

----------------------------------------------------------------------
Ran 9 tests in 0.002s

FAILED (errors=9)
~~~~

**Comment by daler** [comment] 2017-09-05 13:48
@nieder closing this for now. htslib 1.4 should be fine now with pysam; please reopen this if needed.

**Closed by daler** 2017-09-05 13:48 UTC

**Comment by Apteryks** [comment] 2019-02-11 03:51
Hi, the workaround proposed here (to copy the tests somewhere else and run them from there) breaks the following test in version 0.8.0:
```
__________________________ test_getting_example_beds ___________________________

    def test_getting_example_beds():
        assert 'a.bed' in pybedtools.list_example_files()
    
        a_fn = pybedtools.example_filename('a.bed')
>       assert a_fn == os.path.join(testdir, 'data', 'a.bed')
E       AssertionError: assert '/tmp/guix-bu...st/data/a.bed' == '/tmp/test/data/a.bed'
E         - /tmp/guix-build-python-pybedtools-0.8.0.drv-0/pybedtools-0.8.0/build/lib.linux-x86_64-3.7/pybedtools/test/data/a.bed
E         + /tmp/test/data/a.bed

test_helpers.py:151: AssertionError
```

**Comment by imk1** [comment] 2019-11-18 23:06
I am also getting this error:
  from . import scripts
ImportError: cannot import name scripts
I am using a Linux with Centos 6.
