### ISSUE TITLE
MalformedBedLineError: adding a ':' character to the interval? 

### ISSUE THREAD

**Issue by dantaki** [daler/pybedtools#299] opened 2019-10-22 20:49 UTC
I got this error: 

```
pybedtools.cbedtools.MalformedBedLineError: Unable to detect format from ['X', '180652:0', '18065245', '0.640000', '0.360000', '7', '7', '2', '9', '0', '0', '25']
```

Note the start position: `180652:0`

This is the line that's throwing the error:

```
bed = list(BedTool(window_bed).subtract(mask_bed,A=True).nucleotide_content(fi=Meta.fasta))
```

Neither the `window_bed` nor the `mask_bed` files contain this character. Given the interval, it's annotated by the `nuc` command and might have been introduced by it? 

Sometimes I get this bug pop up when running my code. It happens maybe 1 in 10 runs. Is there a way for me to prevent it? 

The correct start position should be `18065220`

**Comment by daler** [comment] 2019-12-25 18:08
I'm unable to reproduce this -- can you provide example input data that reproduces the issue?

**Comment by daler** [comment] 2020-06-02 02:35
Closing for now -- if you can provide a minimally-reproducible example I can take a closer look.

**Closed by daler** 2020-06-02 02:35 UTC
