### ISSUE TITLE
import issue with GLIBC

### ISSUE THREAD

**Issue by radaniba** [daler/pybedtools#187] opened 2016-10-03 23:05 UTC
Hello

I installed pybedtools properly but went through import error

```
>>> import pybedtools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/extscratch/shahlab/raniba/Tasks/2016/virtualenvs/tsp/lib/python2.7/site-packages/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /extscratch/shahlab/raniba/Tasks/2016/virtualenvs/tsp/lib/python2.7/site-packages/pybedtools/cbedtools.so)
>>>
```

Is this related to a dependency or someting.

my default gcc is 5.1.0

Thanks

**Comment by daler** [comment] 2016-10-04 13:32
It sounds like you're using a pybedtools that was compiled somewhere else. Do you have a minimal set of commands I could use to reproduce and debug?

Also if you have `conda` installed, `conda install pybedtools -c bioconda` should work.

**Comment by radaniba** [comment] 2016-10-04 14:50
I installed it via pip, they're not using conda in production though, if cloning the repo and setting up manually will fix that I am going to try it and let you know

**Comment by daler** [comment] 2016-10-04 15:04
Is this in a new virtualenv?

**Comment by radaniba** [comment] 2016-10-04 16:32
yes

**Comment by radaniba** [comment] 2016-10-04 16:58
Ok I tried to install from the github too, cloned the repo and ran manual install

It installs properly but its is not happy on import


```
>>> import pybedtools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: No module named cbedtools
>>>
```

**Comment by daler** [comment] 2016-10-04 19:33
I'm unable to reproduce, bootstrapping the environment from a base Ubuntu:

### Dockerfile
```
FROM ubuntu:latest
RUN apt-get update && apt-get install -y -y \
python \
wget \
curl \
build-essential \
python-dev \
zlib1g-dev
```

### Build
```bash
docker build -t testing .
```

### Test
```bash
docker run -t testing /bin/bash -c "\
wget https://bootstrap.pypa.io/get-pip.py; \
python get-pip.py; \
pip install pybedtools; \
pip install pandas; \
python -c 'import pybedtools; print(pybedtools.__version__)'; \
"
```
### Output
```
--2016-10-04 19:28:51--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.32.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.32.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1524722 (1.5M) [text/x-python]
Saving to: 'get-pip.py'

get-pip.py                             100%[==========================================================================>]   1.45M  --.-KB/s    in 0.05s   

2016-10-04 19:28:51 (30.9 MB/s) - 'get-pip.py' saved [1524722/1524722]

Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 948kB/s 
Collecting setuptools
  Downloading setuptools-28.2.0-py2.py3-none-any.whl (467kB)
    100% |################################| 471kB 2.4MB/s 
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 9.3MB/s 
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-8.1.2 setuptools-28.2.0 wheel-0.29.0
Collecting pybedtools
  Downloading pybedtools-0.7.8.tar.gz (14.5MB)
    100% |################################| 14.6MB 52kB/s 
Collecting six (from pybedtools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pysam (from pybedtools)
  Downloading pysam-0.9.1.4.tar.gz (2.2MB)
    100% |################################| 2.2MB 558kB/s 
Building wheels for collected packages: pybedtools, pysam
  Running setup.py bdist_wheel for pybedtools ... done
  Stored in directory: /root/.cache/pip/wheels/06/6a/ff/a7592ae6146139e33b48d8d65c902e91bddf1d9fad1f66c818
  Running setup.py bdist_wheel for pysam ... /
done
  Stored in directory: /root/.cache/pip/wheels/68/29/e2/51481bb54843c10a1ad89da13c3fbdba643c6b12d3065cbe5b
Successfully built pybedtools pysam
Installing collected packages: six, pysam, pybedtools
Successfully installed pybedtools-0.7.8 pysam-0.9.1.4 six-1.10.0
Collecting pandas
  Downloading pandas-0.19.0-cp27-cp27mu-manylinux1_x86_64.whl (16.3MB)
    100% |################################| 16.3MB 61kB/s 
Collecting pytz>=2011k (from pandas)
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB)
    100% |################################| 481kB 2.4MB/s 
Collecting python-dateutil (from pandas)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |################################| 204kB 5.4MB/s 
Collecting numpy>=1.7.0 (from pandas)
  Downloading numpy-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (15.3MB)
    100% |################################| 15.3MB 71kB/s 
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil->pandas)
Installing collected packages: pytz, python-dateutil, numpy, pandas
Successfully installed numpy-1.11.2 pandas-0.19.0 python-dateutil-2.5.3 pytz-2016.7
0.7.8

```


Based on your last error, are you starting the interpreter from within the pybedtools source dir?  What happens if you try the import from a different working directory? Are you able to run the above test?

**Comment by radaniba** [comment] 2016-10-04 20:09
I see.

The message comes back from whatever directory I launch the interpreter from
I am running on centos5 and not ubuntu so I cannot confirm that the error is reproducible or not on ubuntu :/

**Comment by daler** [comment] 2016-10-04 20:21
CentOS5 comes with Python 2.4, doesn't it? I don't test pybedtools on anything older than 2.7. If you're using an updated Python, how are you managing it? Specifically, would you provide a minimal centos 5 dockerfile that reproduces the error so I can take a look?

**Comment by radaniba** [comment] 2016-10-04 20:23
No actually my python is 2.7.10 but the lab needs pybedtools installed on these machines unfortunately

**Comment by daler** [comment] 2017-04-04 16:08
Closing for now (not intending on supporting python 2.4), but please reopen if needed.

**Closed by daler** 2017-04-04 16:08 UTC
