### ISSUE TITLE
from_dataframe only extracting first character of feature start and end position

### ISSUE THREAD

**Issue by jbhiatt** [daler/pybedtools#321] opened 2020-03-03 17:46 UTC
i am experiencing a very perplexing issue in which the from_dataframe() function is only extracting the first character of the feature start and end position fields. i have tried casting the dataframe columns to a numeric type and that doesnt seem to fix it. code and output below. i am running this in jupyterlab. thanks!

code:
```
print(pd.__version__)
print(pbt.__version__)
print(df.to_csv())
df['start'] = pd.to_numeric(df['start'])
df['end'] = pd.to_numeric(df['end'])
pbt.BedTool.from_dataframe(df).head()
```

output:
1.0.0
0.8.0
,chrom,start,end
0,chr1,17435,17436
1,chr1,29552,29553
2,chr1,30265,30266
3,chr1,30364,30365
4,chr1,36080,36081

chr1	1	1
 chr1	2	2
 chr1	3	3
 chr1	3	3
 chr1	3	3

**Comment by ezotenko-gh** [comment] 2020-03-10 05:24
I am experiencing similar problem with version 0.8.0.  I had to fall back to version 0.7.10 for the `from_dataframe()` method to work as expected.

**Comment by daler** [comment] 2020-06-01 15:06
@jbhiatt, @ezotenko-gh thanks for reporting -- do you have the same issues with v0.8.1? It may have been fixed in https://github.com/daler/pybedtools/commit/a744aee29e795d708c36637b88c7b426ea4189ff. I'm unable to reproduce. If you still have the issue, could you please post a minimally working example that illustrates the problem?

**Closed** 2020-06-18 13:36 UTC
